In [1]:
import pandas as pd
import numpy as np


In [3]:
df = pd.read_parquet('df_reponse_daily_train.parquet')

In [4]:
df.head(5)

stock_id    liq_weight  mktcap_weight  equal_weight  \
time                                                                       
2010-01-04 10:00:00         1  3.093088e+09   7.530677e+10           1.0   
2010-01-04 10:00:00         2  4.916040e+09   1.032883e+11           1.0   
2010-01-04 10:00:00         5  5.239416e+08   5.467715e+09           1.0   
2010-01-04 10:00:00         6  6.517194e+08   5.685524e+09           1.0   
2010-01-04 10:00:00         7  1.407934e+08   1.298457e+09           1.0   

                     21d_next_raw  10d_next_raw  5d_next_raw  1d_next_raw  \
time                                                                        
2010-01-04 10:00:00     -0.109278     -0.105979    -0.054021    -0.047835   
2010-01-04 10:00:00     -0.108716     -0.051546    -0.032802    -0.035614   
2010-01-04 10:00:00     -0.090301      0.021739    -0.013378    -0.016722   
2010-01-04 10:00:00     -0.077609     -0.007136    -0.036574    -0.039251   
2010-01-04 10:00:00      0.004274      0.096866     0.011396    -0.017094   

                     21d_next_mktAdj  10d_next_mktAdj  ...  MOMENTUM  \
time                                                   ...             
2010-01-04 10:00:00        -0.047374        -0.127839  ...  0.737709   
2010-01-04 10:00:00        -0.046811        -0.073406  ... -0.473381   
2010-01-04 10:00:00        -0.028396        -0.000120  ...  1.227050   
2010-01-04 10:00:00        -0.015705        -0.028996  ...  0.396165   
2010-01-04 10:00:00         0.066178         0.075007  ...  0.604593   

                     LEVERAGE     VALUE   EARNYLD    GROWTH  LTREV     STREV  \
time                                                                           
2010-01-04 10:00:00  0.557227 -0.306540 -0.655995  0.214168    0.0  0.572045   
2010-01-04 10:00:00  0.360857  0.466091  0.250722 -0.004936    0.0  1.424041   
2010-01-04 10:00:00 -0.792016 -1.179613 -0.736454 -0.944968    0.0 -0.685017   
2010-01-04 10:00:00  1.905245  0.353328 -0.193752 -0.887294    0.0  1.657673   
2010-01-04 10:00:00  0.467104 -2.195040 -0.370742 -0.951803    0.0  0.873514   

                     industry_code  st_status      price  
time                                                      
2010-01-04 10:00:00             28        0.0  24.250000  
2010-01-04 10:00:00             11        0.0  10.720141  
2010-01-04 10:00:00             11        1.0   5.980000  
2010-01-04 10:00:00             11        0.0  11.282970  
2010-01-04 10:00:00             20        1.0   7.020000  

[5 rows x 31 columns]

In [14]:
# print the industry code
industy_list = list(df['industry_code'].unique())
# there are 30 industry codes from 1 to 30

In [20]:
# group by industry code
df_grouped = df.groupby('industry_code')
# choose 7 as an example cause it has the most data
df_7 = df_grouped.get_group(7)

In [21]:
df_7.columns

Index(['stock_id', 'liq_weight', 'mktcap_weight', 'equal_weight',
       '21d_next_raw', '10d_next_raw', '5d_next_raw', '1d_next_raw',
       '21d_next_mktAdj', '10d_next_mktAdj', '5d_next_mktAdj',
       '1d_next_mktAdj', '21d_next_styAdj', '10d_next_styAdj',
       '5d_next_styAdj', '1d_next_styAdj', 'SIZE', 'SIZENL', 'LIQUIDITY',
       'BETA', 'RESVOL', 'MOMENTUM', 'LEVERAGE', 'VALUE', 'EARNYLD', 'GROWTH',
       'LTREV', 'STREV', 'industry_code', 'st_status', 'price'],
      dtype='object')

In [23]:
# get each stock_id as columns and retrieve the 21d_next_raw as rows
df_7_pivot = df_7.pivot(columns='stock_id', values='21d_next_raw')

In [30]:
# check the na in each columns in df_7_pivot
na_count = df_7_pivot.isna()
a = na_count.sum()
a.describe()


count     363.000000
mean      803.429752
std       659.938397
min         7.000000
25%       215.000000
50%       558.000000
75%      1504.500000
max      1922.000000
dtype: float64

In [37]:
# remove the columns with more than 80% na
df_7_pivot_d = df_7_pivot.dropna(axis=1, thresh=0.6*len(df_7_pivot))
df_7_pivot_d.isna().sum().describe()

count    217.000000
mean     303.331797
std      217.161104
min        7.000000
25%      108.000000
50%      271.000000
75%      485.000000
max      760.000000
dtype: float64

In [31]:
# check the na by index
na_count = df_7_pivot.isna()
a = na_count.sum(axis=1)
a.describe()

count    1923.000000
mean      151.661466
std        15.582726
min       127.000000
25%       142.000000
50%       147.000000
75%       158.000000
max       327.000000
dtype: float64

In [32]:
df_7_0 = df_7_pivot.fillna(0)


In [55]:
factor_return = pd.read_csv('factor_return.csv')



In [41]:
# df_7_0 size
df_7_0.shape

(1923, 363)

In [50]:
# set time as index
# factor_return.set_index('time', inplace=True)
factor_return

fr_21d_next_raw_SIZE  fr_21d_next_raw_SIZENL  \
time                                                                
2010-01-04 10:00:00             -0.029132                0.010736   
2010-01-05 10:00:00             -0.024608                0.004305   
2010-01-06 10:00:00             -0.022657                0.004057   
2010-01-07 10:00:00             -0.025416                0.003620   
2010-01-08 10:00:00             -0.022538                0.000103   
...                                   ...                     ...   
2017-11-24 10:00:00              0.008681                0.002081   
2017-11-27 10:00:00              0.004346               -0.000160   
2017-11-28 10:00:00              0.004398                0.000785   
2017-11-29 10:00:00              0.002810               -0.002403   
2017-11-30 10:00:00              0.005033               -0.001418   

                     fr_21d_next_raw_LIQUIDITY  fr_21d_next_raw_BETA  \
time                                                                   
2010-01-04 10:00:00                   0.001469             -0.013647   
2010-01-05 10:00:00                   0.000982             -0.011989   
2010-01-06 10:00:00                  -0.000720             -0.010729   
2010-01-07 10:00:00                  -0.000475             -0.016114   
2010-01-08 10:00:00                   0.001075             -0.016582   
...                                        ...                   ...   
2017-11-24 10:00:00                   0.005553             -0.004773   
2017-11-27 10:00:00                  -0.000926             -0.002523   
2017-11-28 10:00:00                   0.000653             -0.000009   
2017-11-29 10:00:00                  -0.004188             -0.000888   
2017-11-30 10:00:00                  -0.002825             -0.001134   

                     fr_21d_next_raw_RESVOL  fr_21d_next_raw_MOMENTUM  \
time                                                                    
2010-01-04 10:00:00               -0.021889                  0.002362   
2010-01-05 10:00:00               -0.023065                  0.001797   
2010-01-06 10:00:00               -0.020460                  0.003720   
2010-01-07 10:00:00               -0.019708                  0.002991   
2010-01-08 10:00:00               -0.023129                  0.002498   
...                                     ...                       ...   
2017-11-24 10:00:00               -0.017221                  0.003764   
2017-11-27 10:00:00               -0.011895                  0.009835   
2017-11-28 10:00:00               -0.007344                  0.011960   
2017-11-29 10:00:00               -0.008664                  0.011145   
2017-11-30 10:00:00               -0.009205                  0.011116   

                     fr_21d_next_raw_LEVERAGE  fr_21d_next_raw_VALUE  \
time                                                                   
2010-01-04 10:00:00                 -0.008765               0.003068   
2010-01-05 10:00:00                 -0.002802               0.003228   
2010-01-06 10:00:00                 -0.002388               0.001672   
2010-01-07 10:00:00                 -0.002814               0.002801   
2010-01-08 10:00:00                 -0.005956               0.003846   
...                                       ...                    ...   
2017-11-24 10:00:00                  0.005841              -0.003100   
2017-11-27 10:00:00                  0.002069              -0.004234   
2017-11-28 10:00:00                  0.002907              -0.004090   
2017-11-29 10:00:00                  0.003193              -0.005271   
2017-11-30 10:00:00                  0.000971              -0.004996   

                     fr_21d_next_raw_EARNYLD  fr_21d_next_raw_GROWTH  ...  \
time                                                                  ...   
2010-01-04 10:00:00                 0.011314                0.008238  ...   
2010-01-05 10:00:00                 0.008786                0.006952

In [60]:
inputcsv = pd.concat([df_7_0.reset_index(), factor_return], axis=1, ignore_index=False)
inputcsv

time        36        49        59        96       155  \
0    2010-01-04 10:00:00 -0.126524 -0.108411 -0.015411 -0.073325 -0.085011   
1    2010-01-05 10:00:00 -0.155015 -0.107312 -0.034247 -0.073171 -0.112486   
2    2010-01-06 10:00:00 -0.133436 -0.108614 -0.078061 -0.062025 -0.100559   
3    2010-01-07 10:00:00 -0.130233 -0.135825 -0.079573 -0.060645 -0.107103   
4    2010-01-08 10:00:00 -0.133956 -0.112245  0.000000 -0.048429 -0.094470   
...                  ...       ...       ...       ...       ...       ...   
1918 2017-11-24 10:00:00  0.000000  0.000000  0.000000  0.000000  0.000000   
1919 2017-11-27 10:00:00  0.000000  0.000000  0.000000  0.000000  0.000000   
1920 2017-11-28 10:00:00  0.000000  0.000000  0.000000  0.000000  0.000000   
1921 2017-11-29 10:00:00  0.000000  0.000000  0.000000  0.000000  0.000000   
1922 2017-11-30 10:00:00  0.000000  0.000000  0.000000  0.000000  0.000000   

           407       420       422  498  ...  fr_1d_next_styAdj_BETA  \
0    -0.093714 -0.016187 -0.042593  0.0  ...               -0.001171   
1    -0.111369  0.027322 -0.084862  0.0  ...               -0.003166   
2    -0.084211  0.017921 -0.045326  0.0  ...               -0.000848   
3    -0.083726  0.016304 -0.130776  0.0  ...                0.003387   
4    -0.088000  0.019435 -0.116432  0.0  ...               -0.000743   
...        ...       ...       ...  ...  ...                     ...   
1918  0.000000 -0.071006 -0.042755  0.0  ...                0.000357   
1919  0.000000 -0.087209 -0.065574  0.0  ...                0.001419   
1920  0.000000 -0.059880 -0.053991  0.0  ...                0.001554   
1921  0.000000 -0.068657 -0.044496  0.0  ...               -0.001454   
1922  0.000000 -0.063063 -0.057870  0.0  ...               -0.000609   

      fr_1d_next_styAdj_RESVOL  fr_1d_next_styAdj_MOMENTUM  \
0                    -0.001434                    0.000827   
1                     0.000822                    0.001516   
2                    -0.002019                    0.001960   
3                    -0.001630                    0.002570   
4                     0.001109                    0.002124   
...                        ...                         ...   
1918                 -0.000844                    0.000700   
1919                  0.001636                   -0.001226   
1920                 -0.006217                    0.002545   
1921                  0.000089                    0.001379   
1922                 -0.000217                   -0.000223   

      fr_1d_next_styAdj_LEVERAGE  fr_1d_next_styAdj_VALUE  \
0                       0.001686                 0.001454   
1                      -0.000073                 0.002308   
2                       0.000816                 0.000846   
3                      -0.001164                -0.001094   
4                      -0.001387                 0.001937   
...                          ...                      ...   
1918                   -0.000945                 0.000689   
1919                    0.001032                 0.001669   
1920                    0.000617                -0.000596   
1921                   -0.001933                -0.001083   
1922                    0.001312                -0.000523   

      fr_1d_next_styAdj_EARNYLD  fr_1d_next_styAdj_GROWTH  \
0                      0.001389                 -0.001453   
1                      0.001803                 -0.001870   
2                      0.001288                 -0.000558   
3                     -0.005039                  0.000647   
4                     -0.005148                 -0.001570   
...                         ...                       ...   
1918                  -0.003526                  0.002123   
1919                   0.001303                 -0.000141   
1920                  -0.003434                  0.001033   
1921                   0.003032                 -0.000053   
1922                  -0.000473                 -0.000314   

      f

In [65]:
# change column name time into date
inputcsv.rename(columns={'time':'date', '36':'OT'}, inplace=True)


In [64]:
# 是否存在同一个stockid在不同时间上有不同的industry code
count = 0
df_grouped = df.groupby('stock_id')
for name, group in df_grouped:
    if len(group['industry_code'].unique()) > 1:
        count += 1
        print(name)
        print(group['industry_code'].unique())

print('numbers of different industry',count)


5
[11 16]
6
[11 15]
7
[20 22 12]
8
[22 20 13 12]
9
[11 17]
10
[22 10]
18
[21 22 11 10]
26
[25 21]
30
[25 22 14]
34
[26  3 24]
35
[26  2 16]
36
[ 7 11]
38
[11 22]
40
[22 11]
45
[21 18]
48
[ 3 11]
49
[ 7 18 17]
55
[22  9]
56
[ 5 11]
58
[18  5]
59
[ 7 19]
61
[3 5]
62
[18  5]
68
[18 22 16]
70
[18 26]
96
[ 7 19]
150
[11  4]
151
[22  5]
158
[21 24]
159
[15 19]
301
[5 2]
400
[13 17]
407
[7 2]
409
[22 27]
411
[4 5]
415
[10 29]
416
[ 4  5 29]
421
[ 0 22  2]
426
[ 2 12]
498
[ 7 10]
503
[ 1 24]
506
[11 12]
507
[22  0]
509
[22  9]
511
[11  7]
518
[21  4]
519
[13 12  6]
526
[25 11 20]
529
[21 22]
532
[18 29]
533
[13  8]
534
[ 2 11]
536
[13 18]
541
[18  8]
546
[11 22  9]
547
[22 26  6]
551
[ 2 22 16]
554
[ 7 19]
555
[18 26 24]
561
[ 8 26]
571
[14 15]
576
[30  3 25]
581
[13 14]
587
[25 21]
591
[ 4 17]
592
[25  3]
593
[22  2]
598
[ 2 16]
599
[ 7 14]
602
[12  2]
603
[ 4 12]
605
[ 4  2 16]
606
[ 7  4 24]
607
[ 4 13  1]
611
[13  5 22 15]
615
[ 7 23]
620
[12 22 11]
622
[22 14]
623
[29  4]
626
[3 0]
627
[ 